---
title: "LandRCBM Manual"
subtitle: "`r paste('v.', Sys.getenv('SpadesCBM_MAN_VERSION'))`"
author: "Dominique Caron, Camille Giuliano"
date: "8 May 2026"
output: pdf_document
editor_options: 
  chunk_output_type: console
---
```{r setup-CBM_core, include = FALSE}
```

# LandRCBM_split3pools

:::{.rmdimportant}
This documentation is work in progress. Potential discrepancies and omissions may exist for the time being. If you find any, please contact us [here]("https://github.com/PredictiveEcology/LandRCBM_split3pools/issues").
:::

## Overview

The objective of this module is to make data coming from the `LandR` ecosystem compatible with the `spadesCBM`. The module provides the yearly increments for the three above ground biomass pools: merchantable, foliage, and  other. It does so for the yield tables useful for the spinup event of `spadesCBM`, and for the yearly cohort data which is used for the annual event of `spadesCBM`. The module can also translate disturbances provided by disturbance modules into the format that is expected in `spadesCBM`.

## Inputs

The inputs of `LandRCBM_split3pools` are a combination expected outputs from `LandR`, data to convert total above ground biomass into above merchantable, foliage and other biomass, and data that are expected as input in `spadesCBM`.

The default inputs are for the RIA study area. Most inputs are expected to be provided by other modules (`CBMdefault`, `Biomass_core`, `Biomass_yieldTables`, `Biomass_borealDataPrep`, etc.).

| Name              | Class      | Description                            | Source          |
|-------------------|------------|----------------------------------------|-----------------|
| cohortData        | Data table | Table with cohort-level attributes     | Biomass_borealDataPrep |
| cbm_vars          | list       | List of 4 data tables: parameters, pools, flux, and state | CBM_core |
| pixelGroupMap     | Spatraster | Pixel group map from LandR Groups pixels that share the same cohort composition | Biomass_borealDataPrep |
| rasterToMatch     | SpatRaster | Template raster to use for simulations | User provided   |
| standDT           | Data table | Table of stand attributes. Stands can have 1 or more cohorts | CBM_dataPrep |
| studyArea         | sfc        | Polygon object that defines study area | User provided   |
| table6            | Data table | Boudewyn table used in volume-to-biomass translations | [National Forest Inventory](https://nfi.nfis.org/resources/biomass_models/appendix2_table6.csv)|
| table7            | Data table | Boudewyn table used in volume-to-biomass translations | [National Forest Inventory](https://nfi.nfis.org/resources/biomass_models/appendix2_table7.csv)|
| tableMerchantability | Data table | Parameters for estimation of merchantable proportion of stemwood | [Google Drive](https://drive.google.com/file/d/1wa2QMd7Eo-bPpfigchdpPPPxo7NVpPiC/view?usp=drive_link) |
| yieldTablesCumulative | Data table | Yield tables intended to supply CBM spinup requirements | Biomass_yieldTables |
| yieldTablesId     | Data table | Table spatially linking yield tables to pixels | Biomass_yieldTables |

## Parameters


## Module functioning

### Events

There are 7 events:

1. *init*: Splits the total above ground biomass in yield tables into biomass of each of the three above ground carbon pools.
2. *plotYC*: Plots the yield tables split in above ground carbon pools and the resulting increments.
3. *annualIncrements*: Each time step, compares the `cohortData` with previous year, calculates the difference in biomass for each cohort, and convert this difference into increments of the three above ground carbon pools.
4. *annualDisturbances*: If specified, translates yearly disturbances simulated in other modules into a data.table that can be digested by `CBM_core`.
5. *summarizeAGBPools*: Each time step, summarizes the above ground biomass in each above ground carbon pools for each species across the landscape.
6. *plotMaps*: At a regular interval, maps the above ground biomass and increments of each above carbon pools.
7. *plotSummaries*: At the end of the simulation, plots the evolution of the above ground biomass of each pools for each species and for the entire landscape.

### Plotting

There are 3 types of plots that are created.

First, the modules plots figures related to the yield tables. The module returns a figure for the yield curves of total above ground biomass for a number (controlled by the parameter `numPixGroupPlots`) yield table ids. For the same yield table ids, the module also plots the yield tables divided into above ground carbon pools and the resulting increments.

Second, at a regular interval, controlled by the parameter `.plotInterval`, the modules returns maps of the biomass and increments of merchantable, foliage, and other carbon pools.

Third, at the end of the simulation, the modules returns figures of the evolution of the above ground biomass divided into pools across the landscape for each species.

### Outputs

| Name              | Class      | Description                                                     |
|-------------------|------------|-----------------------------------------------------------------|
| aboveGroundBiomass | Data table | Above ground biomass in each pool for each pixel and cohort    |
| cbm_vars          | List       | List of 4 data tables: parameters, pools, flux, and state       |
| cohortDT          | Data table | Table of cohort-level attributes                                |
| gcIncrements      | Data table | growth increment matrix. Provides increments for each pool in each pixel and cohort |
| gcMeta            | Data table | Growth curve metadata                                           |
| standDT           | Data table | Table of stand attributes. Stands can have 1 or more cohorts    |
| summaryAGB        | Data table | Sum of carbon mass for each species and above ground pools at each time step |
| yieldTablesCumulative | Data table | Yield tables intended to supply CBM spinup requirements     |
| yieldTablesId     | Data table | Table spatially linking yield tables to pixels                  |

### Links to other modules

- [CBM_defaults](https://github.com/PredictiveEcology/CBM_defaults)
- [CBM_datPrep](https://github.com/PredictiveEcology/CBM_dataPrep)
- [CBM_vol2biomass](https://github.com/PredictiveEcology/CBM_vol2biomass)
- [CBM_core](https://github.com/PredictiveEcology/CBM_core)
- [Biomass_borealDataPrep](https://github.com/PredictiveEcology/Biomass_borealDataPrep)
- [Biomass_speciesFactorial](https://github.com/PredictiveEcology/Biomass_borealDataPrep)
- [Biomass_speciesParameters](https://github.com/PredictiveEcology/Biomass_speciesParameters)
- [Biomass_yieldTables](https://github.com/PredictiveEcology/Biomass_yieldTables)
- [Biomass_regeneration](https://github.com/PredictiveEcology/Biomass_regeneration)
- [Biomass_core](https://github.com/PredictiveEcology/Biomass_core)
